Traceback (most recent call last):
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/aciar/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds = xr.open_dataarray('wc2.1_10m_elev.tif')
ds = ds.sel(band=1)
ele_plot = ds.hvplot(x='x',y='y',width=1000,height=500);

dfp = pd.read_csv('occ.csv',index_col=0)
loc_plot = dfp.plot.scatter(x='lon',y='lat');

dfp*loc_plot
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNotImplementedError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 8[0m
[1;32m      5[0m dfp [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m'[39m[38;5;124mocc.csv[39m[38;5;124m'[39m,index_col[38;5;241m=[39m[38;5;241m0[39m)
[1;32m      6[0m loc_plot [38;5;241m=[39m dfp[38;5;241m.[39mplot[38;5;241m.[39mscatter(x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlon[39m[38;5;124m'[39m,y[38;5;241m=[39m[38;5;124m'[39m[38;5;124mlat[39m[38;5;124m'[39m);
[0;32m----> 8[0m [43mdfp[49m[38;5;241;43m*[39;49m[43mloc_plot[49m

File [0;32m/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/pandas/core/ops/common.py:72[0m, in [0;36m_unpack_zerodim_and_defer.<locals>.new_method[0;34m(self, other)[0m
[1;32m     68[0m             [38;5;28;01mreturn[39;00m [38;5;28mNotImplemented[39m
[1;32m     70[0m other [38;5;241m=[39m item_from_zerodim(other)
[0;32m---> 72[0m [38;5;28;01mreturn[39;00m [43mmethod[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mother[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/pandas/core/arraylike.py:118[0m, in [0;36mOpsMixin.__mul__[0;34m(self, other)[0m
[1;32m    116[0m [38;5;129m@unpack_zerodim_and_defer[39m([38;5;124m"[39m[38;5;124m__mul__[39m[38;5;124m"[39m)
[1;32m    117[0m [38;5;28;01mdef[39;00m [38;5;21m__mul__[39m([38;5;28mself[39m, other):
[0;32m--> 118[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_arith_method[49m[43m([49m[43mother[49m[43m,[49m[43m [49m[43moperator[49m[38;5;241;43m.[39;49m[43mmul[49m[43m)[49m

File [0;32m/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/pandas/core/frame.py:7592[0m, in [0;36mDataFrame._arith_method[0;34m(self, other, op)[0m
[1;32m   7589[0m axis [38;5;241m=[39m [38;5;241m1[39m  [38;5;66;03m# only relevant for Series other case[39;00m
[1;32m   7590[0m other [38;5;241m=[39m ops[38;5;241m.[39mmaybe_prepare_scalar_for_op(other, ([38;5;28mself[39m[38;5;241m.[39mshape[axis],))
[0;32m-> 7592[0m [38;5;28mself[39m, other [38;5;241m=[39m [43mops[49m[38;5;241;43m.[39;49m[43malign_method_FRAME[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mother[49m[43m,[49m[43m [49m[43maxis[49m[43m,[49m[43m [49m[43mflex[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m[43m [49m[43mlevel[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m)[49m
[1;32m   7594[0m new_data [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_dispatch_frame_op(other, op, axis[38;5;241m=[39maxis)
[1;32m   7595[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_construct_result(new_data)

File [0;32m/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/pandas/core/ops/__init__.py:277[0m, in [0;36malign_method_FRAME[0;34m(left, right, axis, flex, level)[0m
[1;32m    270[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    271[0m             [38;5;124m"[39m[38;5;124mUnable to coerce to Series/DataFrame, [39m[38;5;124m"[39m
[1;32m    272[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mdimension must be <= 2: [39m[38;5;132;01m{[39;00mright[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m
[1;32m    273[0m         )
[1;32m    275[0m [38;5;28;01melif[39;00m is_list_like(right) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(right, (ABCSeries, ABCDataFrame)):
[1;32m    276[0m     [38;5;66;03m# GH 36702. Raise when attempting arithmetic with list of array-like.[39;00m
[0;32m--> 277[0m     [38;5;28;01mif[39;00m [38;5;28many[39m(is_array_like(el) [38;5;28;01mfor[39;00m el [38;5;129;01min[39;00m right):
[1;32m    278[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    279[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;124mUnable to coerce list of [39m[38;5;132;01m{[39;00m[38;5;28mtype[39m(right[[38;5;241m0[39m])[38;5;132;01m}[39;00m[38;5;124m to Series/DataFrame[39m[38;5;124m"[39m
[1;32m    280[0m         )
[1;32m    281[0m     [38;5;66;03m# GH17901[39;00m

File [0;32m/opt/anaconda3/envs/aciar/lib/python3.11/site-packages/holoviews/core/element.py:94[0m, in [0;36mElement.__iter__[0;34m(self)[0m
[1;32m     92[0m [38;5;28;01mdef[39;00m [38;5;21m__iter__[39m([38;5;28mself[39m):
[1;32m     93[0m     [38;5;124m"[39m[38;5;124mDisable iterator interface.[39m[38;5;124m"[39m
[0;32m---> 94[0m     [38;5;28;01mraise[39;00m [38;5;167;01mNotImplementedError[39;00m([38;5;124m'[39m[38;5;124mIteration on Elements is not supported.[39m[38;5;124m'[39m)

[0;31mNotImplementedError[0m: Iteration on Elements is not supported.

